#! /bin/sh

pgrep -x polybar > /dev/null && killall polybar ; polybar &
~/.autostart  

bspc monitor -d 1 2 3 4
bspc config focus_follows_pointer true
bspc config pointer_modifier     mod1
bspc config border_width         2.5
bspc config border_radius        15
bspc config window_gap           12

bspc config split_ratio          0.5
bspc config presel_feedback_color "#484875"
bspc config focused_border_color "#bd93f9"
bspc config pointer_follows_focus true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
